parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mineroot\WeatherApp\:
        resource: '../src/'
        exclude:
            - '../src/**/Contract'
            - '../src/**/Exception'
            - '../src/**/Object'
            - '../src/**/Request'
            - '../src/**/Response'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Mineroot\WeatherApp\WeatherApi\Client: ~
    Mineroot\WeatherApp\WeatherApi\ClientInterface: '@Mineroot\WeatherApp\WeatherApi\Client'
